general {
    lock_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl output eDP-1 enable 2>/dev/null; hyprctl dispatch dpms on; killall hyprlock 2>/dev/null; hyprlock &
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
