# Auto-generated by apply-ui. DO NOT EDIT DIRECTLY.
# Modify ~/.config/ui/ui.toml and run 'apply-ui'.

export UI_BG_MAIN="#0d1117"
export UI_BG_CARD="#161b22"
export UI_BG_HOVER="#21262d"
export UI_BORDER_COLOR="#30363d"
export UI_ACCENT_BLUE="#58a6ff"
export UI_ACCENT_PURPLE="#bc8cff"
export UI_ACCENT_GREEN="#3fb950"
export UI_WARNING="#d29922"
export UI_CRITICAL="#f85149"
export UI_TEXT_MAIN="#c9d1d9"
export UI_TEXT_DIM="#8b949e"
export UI_TEXT_MUTED="#484f58"

export UI_BORDER_SIZE="2"
export UI_ROUNDING_WINDOW="0"
export UI_ROUNDING_ELEMENT="0"
export UI_ROUNDING_SUBTLE="0"

export SLURP_OPTS='-d -b "#0d1117b0" -c "#58a6ff" -s "#58a6ff20" -w 2 -B "#00000000"'
# Array form for direct use in bash scripts (arrays cannot be exported).
# shellcheck disable=SC2034
SLURP_ARGS=(-d -b "#0d1117b0" -c "#58a6ff" -s "#58a6ff20" -w 2 -B "#00000000")
export UI_FZF_THEME="bg+:#21262d,bg:#0d1117,fg:#c9d1d9,hl:#58a6ff,fg+:#c9d1d9,hl+:#58a6ff,header:#58a6ff,info:#8b949e,pointer:#58a6ff,marker:#3fb950,prompt:#58a6ff,spinner:#58a6ff,border:#30363d"
