# Managed by `wallpaper` — use `wallpaper set` instead of editing manually.
preload = ~/Pictures/Wallpapers/kurzgesagt-04.webp

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/kurzgesagt-04.webp
}

splash = false
ipc = true
