# Managed by `wallpaper` — use `wallpaper set` instead of editing manually.
preload = ~/Pictures/Wallpapers/hyprland.png

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/hyprland.png
}

splash = false
ipc = true
