-- Auto-generated by apply-ui. DO NOT EDIT DIRECTLY.
-- Modify ~/.config/ui/ui.toml and run 'apply-ui'.

return {
    rounding = {
        window = 0,
        element = 0,
        subtle = 0,
    },
    border = {
        size = 2,
    },
    spacing = {
        gaps_in = 10,
        gaps_out = 20,
    },
    opacity = {
        active = 1.0,
        inactive = 0.75,
    },
    font = {
        family = "JetBrainsMono Nerd Font Propo",
        mono = "JetBrainsMono Nerd Font Mono",
        ui = "Adwaita Sans 12",
        size_bar = 15,
        size_menu = 14,
        size_notif = 17,
        size_cursor = 24,
    },
    theme = {
        cursor = "Bibata-Modern-Classic",
        icon = "Papirus-Dark",
        gtk = "Adwaita-dark",
    },
    colors = {
        bg_main = "#0d1117",
        bg_card = "#161b22",
        bg_hover = "#21262d",
        border = "rgba(30363dee)",
        accent_blue = "rgba(58a6ffee)",
        accent_purple = "rgba(bc8cffee)",
        accent_green = "rgba(3fb950ee)",
        warning = "rgba(d29922ee)",
        critical = "rgba(f85149ee)",
        text_main = "#c9d1d9",
        text_dim = "#8b949e",
        text_muted = "#484f58",
        shadow = "rgba(010409ee)",
    },
}
